# Generated by Django 4.0.3 on 2022-04-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default.png', upload_to='images/')),
                ('bio', models.TextField(blank=True, default='Bio', max_length=500)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('contact', models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
