# Generated by Django 4.0.3 on 2022-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
